name: ebisu_rs
version: 0.0.0
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_rs
description: >
  Support for generating rust code
environment:
  sdk: '>=1.8.2 <=2.0.0-dev.20.0'

dependencies:

# custom <ebisu_rs dependencies>

  ebisu: 
    git: 
      url: git://github.com/patefacio/ebisu.git
      ref: dart_1_0

  id:
    git: 
      url: git://github.com/patefacio/id.git
      ref: dart_1_0

  glob: "^1.1.3"

# end <ebisu_rs dependencies>

dev_dependencies:

# custom <ebisu_rs dev dependencies>

  test: "^0.12.20"

  
# end <ebisu_rs dev dependencies>

dependency_overrides:
# custom <ebisu_rs dependency overrides>

# end <ebisu_rs dependency overrides>

transformers:

# custom <ebisu_rs transformers>
# end <ebisu_rs transformers>